#!/usr/bin/env python3
r"""FuchsianCompactCoverBatchTrainer_v1_1.py

Batch generator/trainer for smooth compact finite covers of the existing
regular compact genus-g disk-polygon surfaces.

Scope
-----
* Smooth Riemann surfaces only: the base regular_g surface is torsion-free,
  and every finite-index subgroup/cover of it is torsion-free.
* Explicit Poincare-disk domains only: the cover domain is exported as a
  finite union of translated copies of the base polygon, triangulated for the
  existing GINN sampler.
* No orbifold records and no Teichmuller-space/Fenchel-Nielsen coordinate-only
  records.

Construction
------------
For a base compact surface group generated by the side-pairing labels exported
by FuchsianDomainMaker_v13.make_regular_genus_surface(g), choose an epimorphism
onto a cyclic group Z/n by assigning charges to the side-pairing generators.
The kernel is a finite-index subgroup.  A cover fundamental domain is built as

    union_{q in Z/n} R_q(P_base),

where R_q is a shortest representative word of quotient charge q.  Kernel
side-pairing generators are exported by a Reidemeister-Schreier-style formula

    h(q,x) = R_q x R_{q+phi(x)}^{-1}.

This is deliberately a first conservative compact-cover trainer: cyclic covers
only, small degrees by default, and all generated surfaces are intended as
explicit disk-domain feedstock for GENN branch-geometry experiments.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import importlib.util
import json
import math
import random
import sys
import time
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

PROGRAM = "FuchsianCompactCoverBatchTrainer_v1_1.py"
VERSION = "1.1"


# -----------------------------------------------------------------------------
# Small utilities
# -----------------------------------------------------------------------------


def now_stamp() -> str:
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def safe_label(s: str) -> str:
    out = []
    for ch in str(s):
        if ch.isalnum() or ch in "._-":
            out.append(ch)
        else:
            out.append("_")
    return "".join(out).strip("_") or "run"


def parse_int_list(s: str, default: Sequence[int]) -> List[int]:
    if not str(s or "").strip():
        return list(default)
    vals = []
    for tok in str(s).replace(";", ",").split(","):
        tok = tok.strip()
        if tok:
            vals.append(int(tok))
    return vals


def write_json(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2)


def write_csv(path: Path, rows: List[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        with path.open("w", encoding="utf-8") as f:
            f.write("")
        return
    fields: List[str] = []
    for r in rows:
        for k in r.keys():
            if k not in fields:
                fields.append(k)
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for r in rows:
            w.writerow(r)


def load_module(path: str, name: str) -> Any:
    p = Path(path)
    if not p.exists():
        # Allow relative-to-current-working-directory scripts as the user will run
        # this from the GENN project root.
        p = Path.cwd() / path
    spec = importlib.util.spec_from_file_location(name, p)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not load module from {path}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
    return mod


def complex_to_xy(z: complex) -> List[float]:
    return [float(z.real), float(z.imag)]


def json_complex_pair(v: Sequence[float]) -> complex:
    return complex(float(v[0]), float(v[1]))


# -----------------------------------------------------------------------------
# Minimal SU(1,1) Mobius implementation matching FuchsianDownstairsGINN_v2_4.
# -----------------------------------------------------------------------------


@dataclass(frozen=True)
class SU11:
    alpha: complex
    beta: complex
    word: str = ""

    def __call__(self, z: complex) -> complex:
        den = self.beta.conjugate() * z + self.alpha.conjugate()
        return (self.alpha * z + self.beta) / den

    def det(self) -> float:
        return float(abs(self.alpha) ** 2 - abs(self.beta) ** 2)

    def normalized(self, word: Optional[str] = None) -> "SU11":
        d = self.det()
        if d <= 0 or not math.isfinite(d):
            return SU11(self.alpha, self.beta, self.word if word is None else word)
        s = math.sqrt(d)
        return SU11(self.alpha / s, self.beta / s, self.word if word is None else word)

    def compose(self, other: "SU11", word: Optional[str] = None) -> "SU11":
        # self after other: self(other(z)).
        a1, b1 = self.alpha, self.beta
        a2, b2 = other.alpha, other.beta
        a = a1 * a2 + b1 * b2.conjugate()
        b = a1 * b2 + b1 * a2.conjugate()
        return SU11(a, b, self.word if word is None else word).normalized()

    def inverse(self, word: Optional[str] = None) -> "SU11":
        return SU11(self.alpha.conjugate(), -self.beta, self.word if word is None else word).normalized()

    def as_json(self) -> Dict[str, Any]:
        return {
            "type": "su11",
            "alpha": [float(self.alpha.real), float(self.alpha.imag)],
            "beta": [float(self.beta.real), float(self.beta.imag)],
            "name": self.word,
        }


def su11_from_json(label: str, data: Dict[str, Any]) -> SU11:
    ar, ai = data["alpha"]
    br, bi = data["beta"]
    return SU11(complex(float(ar), float(ai)), complex(float(br), float(bi)), label).normalized(label)


def identity() -> SU11:
    return SU11(1.0 + 0j, 0.0 + 0j, "I")


def mat_key(m: SU11, ndigits: int = 10) -> Tuple[float, float, float, float]:
    mn = m.normalized()
    return (
        round(mn.alpha.real, ndigits), round(mn.alpha.imag, ndigits),
        round(mn.beta.real, ndigits), round(mn.beta.imag, ndigits),
    )


def identity_error(m: SU11) -> float:
    pts = [0+0j, 0.13+0.07j, -0.21+0.19j, 0.32-0.27j]
    return float(max(abs(m(z) - z) for z in pts))


# -----------------------------------------------------------------------------
# Cover construction
# -----------------------------------------------------------------------------


def charge_profiles(num_gens: int, n: int, modes: Sequence[str], rng: random.Random, random_count: int) -> List[Tuple[str, List[int]]]:
    profiles: List[Tuple[str, List[int]]] = []

    def add(name: str, charges: Sequence[int]) -> None:
        c = [int(x) % n for x in charges]
        if len(c) != num_gens:
            return
        if math.gcd(n, *c) != 1:
            return
        # Dedupe up to exact charge vector.  We intentionally do not quotient by
        # mapping-class automorphisms; these are useful regression variants.
        if c not in [p[1] for p in profiles]:
            profiles.append((name, c))

    modes = [m.strip().lower() for m in modes if m.strip()]
    if "basis" in modes:
        for i in range(num_gens):
            c = [0] * num_gens
            c[i] = 1
            add(f"basis{i}", c)
    if "diagonal" in modes:
        add("diag", [1] * num_gens)
    if "alternating" in modes:
        add("alt", [1 if i % 2 == 0 else 0 for i in range(num_gens)])
        add("alt2", [1 if i % 2 == 1 else 0 for i in range(num_gens)])
    if "pair" in modes:
        if num_gens >= 2:
            c = [0] * num_gens
            c[0] = 1
            c[1] = 1
            add("pair01", c)
        if num_gens >= 4:
            c = [0] * num_gens
            c[0] = 1
            c[2] = 1
            add("pair02", c)
    if "random" in modes:
        attempts = max(20, random_count * 20)
        k = 0
        for _ in range(attempts):
            if k >= random_count:
                break
            c = [rng.randrange(n) for _ in range(num_gens)]
            if math.gcd(n, *c) == 1:
                old_len = len(profiles)
                add(f"rand{k}", c)
                if len(profiles) > old_len:
                    k += 1
    return profiles


def bfs_representatives(base_gens: Dict[str, SU11], charges: Dict[str, int], n: int) -> Dict[int, Tuple[Tuple[str, ...], SU11]]:
    moves: List[Tuple[str, int, SU11]] = []
    for lab in sorted(base_gens):
        g = base_gens[lab]
        c = charges[lab] % n
        moves.append((lab, c, g))
        moves.append((lab + "^-1", (-c) % n, g.inverse(lab + "^-1")))
    reps: Dict[int, Tuple[Tuple[str, ...], SU11]] = {0: (tuple(), identity())}
    frontier = [0]
    while frontier and len(reps) < n:
        new_frontier: List[int] = []
        for q in frontier:
            toks, M = reps[q]
            for lab, dc, G in moves:
                nq = (q + dc) % n
                if nq in reps:
                    continue
                reps[nq] = (toks + (lab,), G.compose(M, word=" ".join(toks + (lab,))))
                new_frontier.append(nq)
                if len(reps) >= n:
                    break
            if len(reps) >= n:
                break
        frontier = new_frontier
    if len(reps) != n:
        raise RuntimeError(f"Charges did not generate all residues of Z/{n}; got {len(reps)} residues.")
    return reps


def triangulate_polygon(vertices: List[complex]) -> List[List[complex]]:
    if len(vertices) < 3:
        return []
    out = []
    z0 = vertices[0]
    for i in range(1, len(vertices)-1):
        tri = [z0, vertices[i], vertices[i+1]]
        # Euclidean area threshold is only for sampler stability.
        area2 = abs((tri[1].real-z0.real)*(tri[2].imag-z0.imag) - (tri[1].imag-z0.imag)*(tri[2].real-z0.real))
        if area2 > 1e-14:
            out.append(tri)
    return out


def build_compact_cover_surface(
    maker: Any,
    base_genus: int,
    cover_order: int,
    profile_name: str,
    charges_vec: List[int],
    serial: int,
    max_generators: int = 0,
) -> Dict[str, Any]:
    """Build one compact cyclic cover surface record with explicit audits.

    Mathematical convention:
    - The base is a certified torsion-free compact regular genus-g Fuchsian
      polygon surface.
    - A charge vector defines a homomorphism to Z/n through the abelianization
      of the surface group.  Surjectivity is equivalent to gcd(n, charges)=1.
    - The cover is the kernel subgroup.  Since the base group is torsion-free,
      the kernel is torsion-free; hence the quotient is a smooth compact
      Riemann surface.
    - Exported generators are Reidemeister-Schreier kernel generators. They are
      expected to be redundant and are not claimed to be a minimal canonical
      2g-generator presentation.
    """
    base = maker.make_regular_genus_surface(base_genus)
    base_labels = sorted(str(k) for k in base.get("generators", {}).keys())
    base_gens = {lab: su11_from_json(lab, base["generators"][lab]) for lab in base_labels}
    if len(charges_vec) != len(base_labels):
        raise ValueError("charge vector length does not match base generator count")

    charges = {lab: int(charges_vec[i]) % cover_order for i, lab in enumerate(base_labels)}
    charge_gcd = int(math.gcd(cover_order, *[int(c) for c in charges.values()]))
    charge_surjective = (charge_gcd == 1)
    if not charge_surjective:
        raise ValueError(f"charge vector is not surjective onto Z/{cover_order}; gcd={charge_gcd}")

    reps = bfs_representatives(base_gens, charges, cover_order)

    base_vertices = [json_complex_pair(xy) for xy in base.get("polygon_vertices", [])]
    if len(base_vertices) < 3:
        raise ValueError("Base surface has no polygon vertices")

    # Fundamental domain as triangulated union of translated base polygons.
    tiles: List[Dict[str, Any]] = []
    cover_polygons: List[Dict[str, Any]] = []
    for q in range(cover_order):
        toks, R = reps[q]
        verts = [R(z) for z in base_vertices]
        cover_polygons.append({
            "coset_residue": q,
            "representative_word": " ".join(toks) if toks else "I",
            "vertices": [complex_to_xy(z) for z in verts],
        })
        for j, tri in enumerate(triangulate_polygon(verts)):
            tiles.append({
                "tile_index": len(tiles),
                "tile_kind": "translated_base_polygon_triangle",
                "coset_residue": q,
                "triangle_in_polygon": j,
                "representative_word": " ".join(toks) if toks else "I",
                "vertices": [complex_to_xy(z) for z in tri],
            })

    # Reidemeister-Schreier kernel generators.  We export positive labels only;
    # FuchsianDownstairsGINN adds formal inverses itself.
    kernel_gens: Dict[str, Dict[str, Any]] = {}
    meanings: Dict[str, str] = {}
    seen = set()
    raw_count = 0
    kept = 0
    identity_removed = 0
    duplicate_removed = 0
    truncated_removed = 0
    bad_kernel_charge_count = 0
    max_rs_identity_error = 0.0
    rs_candidate_audit: List[Dict[str, Any]] = []

    for q in range(cover_order):
        _toks_q, Rq = reps[q]
        for lab in base_labels:
            c = charges[lab] % cover_order
            nq = (q + c) % cover_order
            _toks_nq, Rnq = reps[nq]
            kernel_charge = (q + c - nq) % cover_order
            if kernel_charge != 0:
                bad_kernel_charge_count += 1

            H = Rq.compose(base_gens[lab]).compose(Rnq.inverse()).normalized()
            raw_count += 1
            ident_err = identity_error(H)
            max_rs_identity_error = max(max_rs_identity_error, ident_err)
            row: Dict[str, Any] = {
                "source_residue": q,
                "base_generator": lab,
                "base_charge_mod_n": c,
                "target_residue": nq,
                "kernel_charge_mod_n": kernel_charge,
                "identity_error": ident_err,
            }

            if ident_err < 1e-9:
                identity_removed += 1
                row["status"] = "identity_removed"
                rs_candidate_audit.append(row)
                continue

            key = mat_key(H, 10)
            row["matrix_key"] = list(key)
            if key in seen:
                duplicate_removed += 1
                row["status"] = "duplicate_removed"
                rs_candidate_audit.append(row)
                continue
            seen.add(key)

            if max_generators and kept >= max_generators:
                truncated_removed += 1
                row["status"] = "truncated_by_cli_max_generators"
                rs_candidate_audit.append(row)
                continue

            glab = f"k{kept:04d}"
            kernel_gens[glab] = H.normalized(glab).as_json()
            meanings[glab] = f"RS kernel generator R_{q} * {lab} * R_{nq}^-1 for cyclic cover charge {charges[lab]} mod {cover_order}"
            row["status"] = "kept"
            row["exported_label"] = glab
            rs_candidate_audit.append(row)
            kept += 1

    if not kernel_gens:
        raise RuntimeError("No nontrivial kernel generators were exported; cover construction is degenerate.")

    cover_genus = 1 + cover_order * (base_genus - 1)
    expected_cover_genus = cover_genus
    canonical_surface_group_generator_count = 2 * cover_genus
    base_expected_generator_count = 2 * base_genus
    base_area_expected = 4.0 * math.pi * (base_genus - 1)
    base_area = float(base.get("area", base_area_expected))
    area = cover_order * base_area
    expected_area = cover_order * base_area_expected
    gauss_bonnet_area = 4.0 * math.pi * (cover_genus - 1)
    gauss_bonnet_error = abs(area - gauss_bonnet_area)
    gauss_bonnet_relative_error = gauss_bonnet_error / max(1.0, abs(gauss_bonnet_area))

    charge_tag = "_".join(str(c % cover_order) for c in charges_vec)
    sid = f"compact_cover_regg{base_genus}_cyc{cover_order}_{safe_label(profile_name)}_{hashlib.sha1(charge_tag.encode()).hexdigest()[:8]}_n{serial:03d}"

    cover_audit: Dict[str, Any] = {
        "quotient_group": f"Z/{cover_order}Z",
        "cover_degree": cover_order,
        "charge_surjective": charge_surjective,
        "gcd_cover_order_and_charges": charge_gcd,
        "all_rs_candidates_kernel_charge_zero": bad_kernel_charge_count == 0,
        "bad_kernel_charge_count": bad_kernel_charge_count,
        "base_genus": base_genus,
        "cover_genus_formula": "g_cover = 1 + n * (g_base - 1)",
        "expected_cover_genus": expected_cover_genus,
        "reported_cover_genus": cover_genus,
        "genus_formula_error": int(cover_genus - expected_cover_genus),
        "base_area_expected_gauss_bonnet": base_area_expected,
        "base_area_reported": base_area,
        "base_area_error": abs(base_area - base_area_expected),
        "expected_cover_area_from_base": expected_area,
        "reported_cover_area": area,
        "gauss_bonnet_area": gauss_bonnet_area,
        "gauss_bonnet_error": gauss_bonnet_error,
        "gauss_bonnet_relative_error": gauss_bonnet_relative_error,
        "base_generator_count": len(base_labels),
        "expected_base_generator_count_2g": base_expected_generator_count,
        "base_generator_count_matches_2g": len(base_labels) == base_expected_generator_count,
        "canonical_surface_group_generator_count_2g_cover": canonical_surface_group_generator_count,
        "exported_rs_generator_count": len(kernel_gens),
        "rs_generators_are_minimal_canonical_generators": False,
        "rs_generator_warning": "Exported generators are Reidemeister-Schreier kernel generators; they are often redundant and are not asserted to be a minimal 2g generating set.",
        "finite_index_subgroup_of_torsion_free_group": True,
        "torsion_free_reason": "The base regular compact surface group is torsion-free; every subgroup, including this finite-index kernel, is torsion-free.",
        "smooth_riemann_surface": True,
        "orbifold_cone_points": 0,
        "cusps": 0,
        "compact": True,
    }

    sj: Dict[str, Any] = {
        "format": "FuchsianGENN compact cyclic cover surface JSON v1.1",
        "surface_id": sid,
        "name": f"Compact cyclic degree-{cover_order} cover of regular genus-{base_genus} surface ({profile_name})",
        "surface_family": "compact_cyclic_cover_regular_polygon",
        "category": "compact_cyclic_cover_regular_polygon",
        "domain_type": "compact_cover_tile_union",
        "compact": True,
        "mainline_dataset_eligible": True,
        "riemann_surface_status": "smooth compact hyperbolic Riemann surface; finite unramified cover of a torsion-free compact base surface",
        "kahler_status": "compact Riemann surface; Kähler automatically in complex dimension one",
        "mathematical_object": "smooth compact finite cover of a regular polygon Fuchsian surface",
        "certification_level": "cyclic_finite_cover_of_certified_regular_genus_surface_with_v1_1_audits",
        "certification": {
            "status": "constructed_cyclic_cover_of_torsion_free_compact_surface",
            "construction": "kernel of a surjective homomorphism from the base side-pairing group to Z/n, exported with translated base-polygon fundamental domain and RS kernel generators",
            "audit": "v1.1 records charge surjectivity, genus formula, Gauss-Bonnet area error, SU(1,1) determinant errors, and RS kernel-charge checks",
            "warning": "v1.1 supports cyclic cover quotients only; it includes explicit cover/genus/area/RS-kernel audit fields and is intended as explicit disk-domain GENN feedstock rather than a named algebraic curve identifier.",
        },
        "smooth_surface_audit": {
            "smooth_riemann_surface": True,
            "compact": True,
            "cusps": 0,
            "orbifold_cone_points": 0,
            "base_declared_torsion_free": True,
            "subgroup_declared_torsion_free": True,
            "unramified_cover": True,
        },
        "cover_audit": cover_audit,
        "base_surface": {
            "surface": f"regular_g{base_genus}",
            "genus": base_genus,
            "sides": base.get("sides"),
            "area": base_area,
            "generator_labels": base_labels,
            "generator_count": len(base_labels),
        },
        "cover_group": "cyclic",
        "cover_order": cover_order,
        "cover_degree": cover_order,
        "genus": cover_genus,
        "area": area,
        "gauss_bonnet_area": gauss_bonnet_area,
        "gauss_bonnet_error": gauss_bonnet_error,
        "base_charge_profile": profile_name,
        "charge_vector_mod_n": [int(c) % cover_order for c in charges_vec],
        "charge_labels": {lab: charges[lab] for lab in base_labels},
        "quotient_residue_count": cover_order,
        "coset_representatives": [
            {"residue": q, "word": (" ".join(reps[q][0]) if reps[q][0] else "I")}
            for q in range(cover_order)
        ],
        "cover_polygons": cover_polygons,
        "fundamental_domain_tiles": tiles,
        "generators": kernel_gens,
        "generator_meanings": meanings,
        "rs_candidate_audit": rs_candidate_audit,
        "generator_export_audit": {
            "raw_rs_generator_candidates": raw_count,
            "exported_generator_count": len(kernel_gens),
            "identity_candidates_removed": identity_removed,
            "duplicate_candidates_removed": duplicate_removed,
            "truncated_candidates_removed": truncated_removed,
            "unique_nonidentity_matrix_count_before_truncation": len(seen),
            "deduplicated_matrix_count": len(seen),
            "truncated_by_cli_max_generators": bool(max_generators and truncated_removed > 0),
            "cli_max_generators": max_generators,
            "all_exported_generators_have_kernel_charge_zero": bad_kernel_charge_count == 0,
            "bad_kernel_charge_count": bad_kernel_charge_count,
            "max_rs_identity_error": max_rs_identity_error,
            "label_scheme": "k0000, k0001, ... with formal inverses added by FuchsianDownstairsGINN",
            "minimality_warning": "The RS set is a valid exported kernel generating set, not a minimal canonical side-pairing set.",
        },
        "triangulation_audit": {
            "translated_base_polygons": cover_order,
            "triangle_tiles": len(tiles),
            "base_polygon_vertices": len(base_vertices),
            "domain_area_is_n_times_base_area": True,
        },
        "source_program": PROGRAM,
        "source_version": VERSION,
        "notes": "Compact cyclic-cover trainer v1.1 with cover and Reidemeister-Schreier audit fields. The cover domain is a tile union, so the GINN sampler should use fundamental_domain_tiles rather than polygon_vertices.",
    }
    return sj

def generator_su11_audit(sj: Dict[str, Any]) -> Dict[str, Any]:
    max_det = 0.0
    bad = 0
    for lab, g in sj.get("generators", {}).items():
        M = su11_from_json(str(lab), g)
        err = abs(M.det() - 1.0)
        max_det = max(max_det, err)
        if err > 1e-6:
            bad += 1
    return {"generator_count": len(sj.get("generators", {})), "bad_generator_count": bad, "su11_max_det_error": max_det}


def audit_surface(sj: Dict[str, Any]) -> Dict[str, Any]:
    su = generator_su11_audit(sj)
    ca = sj.get("cover_audit", {}) or {}
    gea = sj.get("generator_export_audit", {}) or {}
    return {
        "surface_id": sj.get("surface_id"),
        "family": sj.get("surface_family"),
        "base_genus": sj.get("base_surface", {}).get("genus"),
        "cover_order": sj.get("cover_order"),
        "cover_genus": sj.get("genus"),
        "expected_cover_genus": ca.get("expected_cover_genus"),
        "genus_formula_error": ca.get("genus_formula_error"),
        "area": sj.get("area"),
        "gauss_bonnet_area": ca.get("gauss_bonnet_area", sj.get("gauss_bonnet_area")),
        "gauss_bonnet_error": ca.get("gauss_bonnet_error", sj.get("gauss_bonnet_error")),
        "gauss_bonnet_relative_error": ca.get("gauss_bonnet_relative_error"),
        "charge_profile": sj.get("base_charge_profile"),
        "charge_vector_mod_n": json.dumps(sj.get("charge_vector_mod_n")),
        "charge_surjective": ca.get("charge_surjective"),
        "gcd_cover_order_and_charges": ca.get("gcd_cover_order_and_charges"),
        "all_rs_candidates_kernel_charge_zero": ca.get("all_rs_candidates_kernel_charge_zero"),
        "bad_kernel_charge_count": ca.get("bad_kernel_charge_count"),
        "base_generator_count": ca.get("base_generator_count"),
        "expected_base_generator_count_2g": ca.get("expected_base_generator_count_2g"),
        "base_generator_count_matches_2g": ca.get("base_generator_count_matches_2g"),
        "canonical_surface_group_generator_count_2g_cover": ca.get("canonical_surface_group_generator_count_2g_cover"),
        "generators": su.get("generator_count"),
        "exported_rs_generator_count": ca.get("exported_rs_generator_count"),
        "rs_generators_are_minimal_canonical_generators": ca.get("rs_generators_are_minimal_canonical_generators"),
        "raw_rs_generator_candidates": gea.get("raw_rs_generator_candidates"),
        "identity_candidates_removed": gea.get("identity_candidates_removed"),
        "duplicate_candidates_removed": gea.get("duplicate_candidates_removed"),
        "truncated_candidates_removed": gea.get("truncated_candidates_removed"),
        "bad_generators": su.get("bad_generator_count"),
        "su11_max_det_error": su.get("su11_max_det_error"),
        "smooth_riemann_surface": ca.get("smooth_riemann_surface"),
        "orbifold_cone_points": ca.get("orbifold_cone_points"),
        "cusps": ca.get("cusps"),
        "compact": ca.get("compact"),
        "translated_base_polygons": sj.get("triangulation_audit", {}).get("translated_base_polygons"),
        "triangle_tiles": sj.get("triangulation_audit", {}).get("triangle_tiles"),
        "mainline_dataset_eligible": sj.get("mainline_dataset_eligible"),
    }


# -----------------------------------------------------------------------------
# Direct GINN integration, matching the exploratory modular permutation trainer.
# -----------------------------------------------------------------------------


def run_direct_ginn(ginn: Any, sj: Dict[str, Any], run_root: Path, args: argparse.Namespace) -> Dict[str, Any]:
    t0 = time.time()
    sid = str(sj.get("surface_id"))
    outdir = run_root / "ginn_runs" / sid
    outdir.mkdir(parents=True, exist_ok=True)
    try:
        rows, X, D, word_ball, label_meta, feature_names = ginn.generate_ginn_dataset(
            sj, args.pairs, args.depth, args.seed, max_word_ball=args.max_word_ball
        )
        write_json(outdir / "surface.json", sj)
        write_json(outdir / "label_meta.json", label_meta)
        metrics = ginn.train_ginn(
            rows, X, D, word_ball, outdir, args.depth, args.epochs,
            args.pair_hidden, args.score_hidden, args.lr,
            args.batch_size, args.seed, args.device, args.patience,
            args.ce_weight, args.soft_distance_weight, args.temperature,
            candidate_chunk_size=args.candidate_chunk_size,
            auto_chunk_threshold_mb=args.auto_chunk_threshold_mb,
        )
        return {
            "surface_id": sid,
            "returncode": 0,
            "wall_seconds": time.time() - t0,
            "pass_ginn_training": True,
            "word_ball_size": metrics.get("word_ball_size"),
            "winning_lift_accuracy_test": metrics.get("winning_lift_accuracy_test"),
            "winning_lift_top5_accuracy_test": metrics.get("winning_lift_top5_accuracy_test"),
            "shortcut_fraction_test": metrics.get("shortcut_fraction_test"),
            "error": "",
        }
    except Exception as e:
        return {
            "surface_id": sid,
            "returncode": 1,
            "wall_seconds": time.time() - t0,
            "pass_ginn_training": False,
            "error": f"{type(e).__name__}: {e}",
        }


# -----------------------------------------------------------------------------
# CLI
# -----------------------------------------------------------------------------


def profile_defaults(profile: str) -> Dict[str, Any]:
    if profile == "smoke":
        return {"base_genera": [2], "cover_orders": [2], "charge_modes": ["basis"], "profiles_per_pair": 1, "pairs": 500, "epochs": 3}
    if profile == "small":
        return {"base_genera": [2, 3], "cover_orders": [2, 3], "charge_modes": ["basis", "diagonal"], "profiles_per_pair": 2, "pairs": 3000, "epochs": 30}
    if profile == "balanced":
        return {"base_genera": [2, 3, 4], "cover_orders": [2, 3, 4], "charge_modes": ["basis", "diagonal", "alternating", "pair"], "profiles_per_pair": 4, "pairs": 9000, "epochs": 80}
    if profile == "wide":
        return {"base_genera": [2, 3, 4, 5], "cover_orders": [2, 3, 4, 5, 6], "charge_modes": ["basis", "diagonal", "alternating", "pair", "random"], "profiles_per_pair": 6, "pairs": 9000, "epochs": 80}
    return {"base_genera": [2], "cover_orders": [2], "charge_modes": ["basis"], "profiles_per_pair": 1, "pairs": 9000, "epochs": 80}


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="Compact cyclic-cover batch trainer for regular compact Fuchsian surfaces")
    ap.add_argument("--profile", default="balanced", choices=["smoke", "small", "balanced", "wide", "manual"])
    ap.add_argument("--base-genera", default="", help="comma-list override, e.g. 2,3,4")
    ap.add_argument("--cover-orders", default="", help="comma-list override, e.g. 2,3,4")
    ap.add_argument("--charge-modes", default="", help="comma-list among basis,diagonal,alternating,pair,random")
    ap.add_argument("--profiles-per-pair", type=int, default=0, help="cap charge profiles per (base genus, cover order); 0 uses profile default")
    ap.add_argument("--random-charge-count", type=int, default=4)
    ap.add_argument("--max-surfaces", type=int, default=0, help="0 means no cap")
    ap.add_argument("--max-cover-genus", type=int, default=999999)
    ap.add_argument("--maker", default="FuchsianDomainMaker_v13.py")
    ap.add_argument("--ginn-script", default="FuchsianDownstairsGINN_v2_4.py")
    ap.add_argument("--outroot", default="compact_cover_batch_runs")
    ap.add_argument("--label", default="")
    ap.add_argument("--run-ginn", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--pairs", type=int, default=0)
    ap.add_argument("--depth", type=int, default=2)
    ap.add_argument("--max-word-ball", type=int, default=50000)
    ap.add_argument("--epochs", type=int, default=0)
    ap.add_argument("--batch-size", type=int, default=64)
    ap.add_argument("--device", default="auto")
    ap.add_argument("--pair-hidden", type=int, default=192)
    ap.add_argument("--score-hidden", type=int, default=96)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--patience", type=int, default=15)
    ap.add_argument("--ce-weight", type=float, default=1.0)
    ap.add_argument("--soft-distance-weight", type=float, default=0.2)
    ap.add_argument("--temperature", type=float, default=1.0)
    ap.add_argument("--candidate-chunk-size", type=int, default=8192)
    ap.add_argument("--auto-chunk-threshold-mb", type=float, default=2048.0)
    ap.add_argument("--max-generators", type=int, default=0)
    ap.add_argument("--seed", type=int, default=12345)
    args = ap.parse_args(argv)

    defaults = profile_defaults(args.profile)
    base_genera = parse_int_list(args.base_genera, defaults["base_genera"])
    cover_orders = parse_int_list(args.cover_orders, defaults["cover_orders"])
    charge_modes = [x.strip() for x in (args.charge_modes or ",".join(defaults["charge_modes"])).split(",") if x.strip()]
    profiles_per_pair = args.profiles_per_pair if args.profiles_per_pair > 0 else int(defaults["profiles_per_pair"])
    if args.pairs <= 0:
        args.pairs = int(defaults["pairs"])
    if args.epochs <= 0:
        args.epochs = int(defaults["epochs"])

    label = safe_label(args.label or f"{args.profile}_compact_covers")
    run_root = Path(args.outroot) / f"run_{now_stamp()}_{label}"
    (run_root / "surfaces").mkdir(parents=True, exist_ok=True)
    (run_root / "tables").mkdir(parents=True, exist_ok=True)

    rng = random.Random(args.seed)
    maker = load_module(args.maker, "fuchsian_domain_maker_compact_cover")
    ginn = load_module(args.ginn_script, "ginn_v24_compact_cover") if args.run_ginn and not args.dry_run else None

    surface_rows: List[Dict[str, Any]] = []
    train_rows: List[Dict[str, Any]] = []
    manifest_surfaces: List[str] = []
    serial = 0
    stop = False

    for bg in base_genera:
        for n in cover_orders:
            cover_genus = 1 + n * (bg - 1)
            if cover_genus > args.max_cover_genus:
                continue
            # Need base surface to know number of side-pairing labels.
            base = maker.make_regular_genus_surface(bg)
            num_gens = len(base.get("generators", {}))
            profiles = charge_profiles(num_gens, n, charge_modes, rng, args.random_charge_count)
            if profiles_per_pair:
                profiles = profiles[:profiles_per_pair]
            for pname, charges in profiles:
                if args.max_surfaces and serial >= args.max_surfaces:
                    stop = True
                    break
                try:
                    sj = build_compact_cover_surface(
                        maker, bg, n, pname, charges, serial,
                        max_generators=args.max_generators,
                    )
                    sid = str(sj["surface_id"])
                    manifest_surfaces.append(sid)
                    surface_rows.append(audit_surface(sj))
                    write_json(run_root / "surfaces" / f"{sid}.json", sj)
                    print(f"[surface] {sid} genus={sj.get('genus')} generators={len(sj.get('generators', {}))} tiles={len(sj.get('fundamental_domain_tiles', []))}", flush=True)
                    if args.run_ginn and not args.dry_run and ginn is not None:
                        tr = run_direct_ginn(ginn, sj, run_root, args)
                        train_rows.append({**audit_surface(sj), **tr})
                        print(f"[train] {sid} ok={tr.get('pass_ginn_training')} top1={tr.get('winning_lift_accuracy_test')} top5={tr.get('winning_lift_top5_accuracy_test')} err={str(tr.get('error',''))[:120]}", flush=True)
                    serial += 1
                except Exception as e:
                    err_sid = f"compact_cover_regg{bg}_cyc{n}_{safe_label(pname)}_n{serial:03d}"
                    row = {
                        "surface_id": err_sid,
                        "base_genus": bg,
                        "cover_order": n,
                        "charge_profile": pname,
                        "pass_surface_generation": False,
                        "error": f"{type(e).__name__}: {e}",
                    }
                    surface_rows.append(row)
                    print(f"[surface-error] {err_sid}: {row['error']}", flush=True)
                    serial += 1
            if stop:
                break
        if stop:
            break

    write_csv(run_root / "tables" / "compact_cover_surfaces.csv", surface_rows)
    if train_rows:
        write_csv(run_root / "tables" / "compact_cover_training.csv", train_rows)
    write_json(run_root / "manifest.json", {
        "program": PROGRAM,
        "version": VERSION,
        "created": datetime.now().isoformat(timespec="seconds"),
        "profile": args.profile,
        "base_genera": base_genera,
        "cover_orders": cover_orders,
        "charge_modes": charge_modes,
        "profiles_per_pair": profiles_per_pair,
        "surfaces": manifest_surfaces,
        "run_ginn": args.run_ginn,
        "dry_run": args.dry_run,
        "pairs": args.pairs,
        "depth": args.depth,
        "epochs": args.epochs,
        "max_word_ball": args.max_word_ball,
    })

    ok = sum(1 for r in train_rows if r.get("pass_ginn_training"))
    report = run_root / "compact_cover_batch_report.md"
    lines = [
        "# Compact Cover Batch Trainer Report\n\n",
        f"Program: `{PROGRAM}` v{VERSION}\n\n",
        "## Scope\n\n",
        "Smooth compact Riemann surfaces only. Each animal is a finite cyclic cover of a certified regular compact genus-g disk-polygon surface. The exported domain is an explicit triangulated union of translated base polygons in the Poincare disk. No orbifold records and no Teichmuller-space-only records are included.\n\n",
        "## Summary\n\n",
        f"- Generated/attempted surfaces: **{len(surface_rows)}**\n",
        f"- Successfully generated surfaces: **{len(manifest_surfaces)}**\n",
        f"- Run GINN: `{args.run_ginn}`\n",
        f"- Dry run: `{args.dry_run}`\n",
        f"- Training successes: `{ok}/{len(train_rows)}`\n\n",
        "## Surfaces and audit fields\n\n",
        "| surface_id | base genus | cover order | cover genus | profile | charge vector | charge onto? | GB error | RS kernel ok? | exported RS gens | canonical 2g | tiles |\n",
        "| --- | ---: | ---: | ---: | --- | --- | --- | ---: | --- | ---: | ---: | ---: |\n",
    ]
    for r in surface_rows:
        lines.append(
            f"| `{r.get('surface_id','')}` | {r.get('base_genus','')} | {r.get('cover_order','')} | {r.get('cover_genus','')} | "
            f"{r.get('charge_profile','')} | `{r.get('charge_vector_mod_n','')}` | {r.get('charge_surjective','')} | "
            f"{r.get('gauss_bonnet_error','')} | {r.get('all_rs_candidates_kernel_charge_zero','')} | "
            f"{r.get('generators','')} | {r.get('canonical_surface_group_generator_count_2g_cover','')} | {r.get('triangle_tiles','')} |\n"
        )
    lines.extend([
        "\n## Mathematical audit notes\n\n",
        "- `charge onto?` checks that the charge vector is surjective onto the cyclic quotient `Z/n`; equivalently `gcd(n, charges)=1`.\n",
        "- `GB error` is `|reported_area - 4*pi*(cover_genus-1)|`. This should be near numerical zero.\n",
        "- `RS kernel ok?` checks that every Reidemeister-Schreier candidate has zero quotient charge modulo `n`.\n",
        "- `exported RS gens` is not expected to equal `canonical 2g`. These are Reidemeister-Schreier kernel generators and may be redundant.\n",
    ])
    if train_rows:
        lines.extend([
            "\n## Training results\n\n",
            "| surface_id | pass | word ball | top1 | top5 | shortcut fraction | seconds | error |\n",
            "| --- | --- | ---: | ---: | ---: | ---: | ---: | --- |\n",
        ])
        for r in train_rows:
            lines.append(
                f"| `{r.get('surface_id','')}` | {r.get('pass_ginn_training')} | {r.get('word_ball_size','')} | "
                f"{r.get('winning_lift_accuracy_test','')} | {r.get('winning_lift_top5_accuracy_test','')} | {r.get('shortcut_fraction_test','')} | "
                f"{r.get('wall_seconds','')} | {str(r.get('error','')).replace('|','/')[:120]} |\n"
            )
    report.write_text("".join(lines), encoding="utf-8")
    print(f"[done] report={report}", flush=True)
    return 0 if all(r.get("pass_ginn_training", True) for r in train_rows) else 1


if __name__ == "__main__":
    raise SystemExit(main())
